# Permissions for end users to view ScheduledSparkApplications.
# Aggregated to the default "view" ClusterRole.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduledsparkapplication-viewer-role
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/managed-by: kustomize
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups:
      - sparkoperator.k8s.io
    resources:
      - scheduledsparkapplications
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - sparkoperator.k8s.io
    resources:
      - scheduledsparkapplications/status
    verbs:
      - get
